#日志
logging:
  file:
    path: ../logs

server:
  port: 9003
#spring
spring:
  application:
    name: chao-ssh
  aop:  
    auto: true
  output:
    ansi:
      enabled: always 
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource: #数据库连接设置
    platform: h2
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ssh;MODE=MYSQL
    username: root
    password: root
    schema: classpath:sql/schema.sql
    data: classpath:sql/data.sql
  thymeleaf:
    mode: LEGACYHTML5
    cache: false   
  
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl:  com.chao.cloud.common.extra.mybatis.log.Slf4jLogImpl
            